blog_app:
    class: Statocles::App::Blog
    args:
        store: 'blog'
        url_root: /blog

basic_app:
    class: Statocles::App::Basic
    args:
        store: '.'
        url_root: '/'

site:
    class: Statocles::Site
    args:
        title: Chicago.PM
        base_url: http://chicago.pm.org
        theme: 'theme'
        nav:
            main:
                - title: Meetup
                  href: http://www.meetup.com/ChicagoPM
                - title: Github
                  href: http://github.com/ChicagoPM
                - title: Talks
                  href: /talks
                - title: Meeting Notes
                  href: /notes
                - title: Jobs
                  href: /jobs
                - title: About
                  href: /about
                - title: Mailing List
                  href: /about#lists
                - title: How To
                  href: /howto
        deploy:
            $class: Statocles::Deploy::Git
        index: /blog
        apps:
            basic:
                $ref: basic_app
            blog:
                $ref: blog_app
